# ==============================================================================
# Common configuration
# ==============================================================================
# Shared paths and settings used by every build fragment.

WORKSPACE := /workspace

# Number of parallel jobs. Defaults to every CPU visible inside the container.
# Override from the command line, e.g. `make build-minui JOBS=4`.
JOBS ?= $(shell nproc)
JOBS := 4

# Cross-compilation target generated by crosstool-NG.
TARGET := arm-unknown-linux-gnueabi

TOOLCHAIN_ROOT := $(WORKSPACE)/toolchain
TOOLCHAIN_PREFIX := $(TOOLCHAIN_ROOT)/$(TARGET)
TOOLCHAIN_BIN := $(TOOLCHAIN_PREFIX)/bin
TOOLCHAIN_SYSROOT := $(TOOLCHAIN_PREFIX)/$(TARGET)/sysroot

# Stable aliases used by library builds.
INSTALL_BIN := $(TOOLCHAIN_ROOT)/bin
CROSS_COMPILE := $(INSTALL_BIN)/$(TARGET)-

# Final sysroot used by projects. It starts as a copy of the crosstool-NG
# sysroot and is enriched with SDL, zlib, tinyalsa, etc.
SYSROOT := $(WORKSPACE)/sysroot

# Temporary sysroot used while rebuilding all common libraries. This prevents
# `make build-libs` from depending on libraries left by an earlier install.
BUILD_SYSROOT := $(WORKSPACE)/build/sysroot

# Legacy Trimui projects hard-code this Buildroot-style toolchain location.
# toolchain.mk creates wrappers/symlinks here without modifying upstream code.
COMPAT_TOOLCHAIN := /opt/trimui-toolchain
COMPAT_BIN := $(COMPAT_TOOLCHAIN)/bin
COMPAT_TARGET := arm-buildroot-linux-gnueabi

# Reserved for final packaged artifacts. Once every standalone emulator and
# PicoArch is handled, a global release target can collect their packages here.
OUTPUT_DIR := $(WORKSPACE)/output
FINAL_RELEASE_DIR := $(OUTPUT_DIR)/release
